# .github/workflows/upyun.yml
name: upyun

on:
  workflow_dispatch:

jobs:
  douban:
    name: upyun data sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        path: /box

      - name: compare
        uses: binjoo/action@main
        with:
          upyun_dir: ${{ secrets.UPYUN_DIR }}
          upyun_bucket: ${{ secrets.UPYUN_BUCKET }}
          upyun_username: ${{ secrets.UPYUN_USERNAME }}
          upyun_password: ${{ secrets.UPYUN_PASSWORD }}

      - name: Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: "chore: update upyun data"
          add: "./box"
